"""empty message

Revision ID: 4d126b37beb8
Revises: 
Create Date: 2024-11-16 15:06:18.718136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d126b37beb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('image_filename', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destination_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_country'), ['country'], unique=True)
        batch_op.create_index(batch_op.f('ix_destination_state'), ['state'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destination_state'))
        batch_op.drop_index(batch_op.f('ix_destination_country'))
        batch_op.drop_index(batch_op.f('ix_destination_city'))

    op.drop_table('destination')
    # ### end Alembic commands ###
