"""empty message

Revision ID: 50e907c5578d
Revises: 4fbf8bd5e983
Create Date: 2024-11-15 20:45:43.147624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e907c5578d'
down_revision = '4fbf8bd5e983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=513),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=513),
               existing_nullable=True)

    # ### end Alembic commands ###
