name: Python CI

on:
  push:
    branches:
      - main
      - Terence_Tester
  pull_request:
    branches:
      - main
      - Terence_Tester

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: List directory structure for debugging
        run: |
          ls -R .  # Lists all files to confirm structure

      - name: Set up Database Path
        run: |
          mkdir -p src/instance
        env:
          SQLALCHEMY_DATABASE_URI: sqlite:///src/instance/trip_planner.db

      - name: Initialize Database
        run: |
          python -c "from main_menu import db; db.create_all()"
        env:
          PYTHONPATH: "${{ github.workspace }}/src"
          SQLALCHEMY_DATABASE_URI: sqlite:///src/instance/trip_planner.db

      - name: Start server
        run: |
          nohup python src/main_menu.py &  # Start the server in the background
          sleep 5  # Wait a few seconds to ensure the server starts

      - name: Verify server is running
        run: |
          ps aux | grep main_menu.py
          netstat -an | grep 5000

      - name: Run tests
        run: pytest test/
