name: Python CI

on:
  push:
    branches:
      - main
      - Terence_Tester
  pull_request:
    branches:
      - main
      - Terence_Tester

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start the backend server
        run: |
          python src/your_server_file.py &  # replace with your actual server start command
          sleep 5  # wait a few seconds to ensure the server is running

      - name: Run tests
        run: pytest test/
