name: Python CI

on:
  push:
    branches:
      - main
      - Terence_Tester
  pull_request:
    branches:
      - main
      - Terence_Tester

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server
        run: |
          nohup python src/main_menu.py &  # Adjust the path if needed
          sleep 5  # Wait a few seconds to ensure the server starts

      - name: Run tests
        run: pytest test/  # Adjust this path if your test files are in a different directory
