name: Python CI

on:
  push:
    branches:
      - main
      - Terence_Tester
  pull_request:
    branches:
      - main
      - Terence_Tester

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start server  # New step to start the server
        run: |
          nohup python src/app.py &  # Adjust the path and command as necessary
        # Start in the background with 'nohup' so it doesn't block the next steps

      - name: Run tests
        run: pytest test/  # Adjust this path if your test files are in a different directory
