name: Python CI

on:
  push:
    branches:
      - main
      - Terence_Tester
  pull_request:
    branches:
      - main
      - Terence_Tester

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize Database
        run: python -c "from main_menu import db; db.create_all()"  # Ensures the database and tables are created

      - name: Start server
        run: |
          nohup python src/main_menu.py &  # Start the server in the background
          sleep 5  # Wait a few seconds to ensure the server starts

      - name: Verify server is running
        run: |
          ps aux | grep main_menu.py     # Check if the server process is running
          netstat -an | grep 5000        # Check if port 5000 is listening

      - name: Run tests
        run: pytest test/  # Adjust this path if your test files are in a different directory
